<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="dog">

  <!-- ===== параметры ===== -->
  <xacro:property name="body_length" value="0.475"/>
  <xacro:property name="body_width"  value="0.18"/>
  <xacro:property name="body_height" value="0.10"/>
  <xacro:property name="thigh_length" value="0.144"/>
  <xacro:property name="shin_length" value="0.1525"/>
  <xacro:property name="leg_radius" value="0.02"/>
  <xacro:property name="leg_mass" value="0.2"/>

  <!-- ===== base_link ===== -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="gray"><color rgba="0.5 0.5 0.5 1"/></material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  <!-- ===== макрос лапы (hip-thigh-shin) ===== -->
  <xacro:macro name="leg" params="name x y">
    <!-- hip -->
    <link name="${name}_hip">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${leg_radius}" length="0.05"/>
        </geometry>
        <material name="black"><color rgba="0 0 0 1"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${leg_radius}" length="0.05"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${leg_mass}"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      </inertial>
    </link>

    <joint name="${name}_hip_joint" type="revolute">
      <parent link="base_link"/>
      <child  link="${name}_hip"/>
      <origin xyz="${x} ${y} 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="-1.57" upper="1.57" effort="10" velocity="1"/>
    </joint>

    <!-- thigh -->
    <link name="${name}_thigh">
      <visual>
        <origin xyz="0 0 -${thigh_length/2.0}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${leg_radius}" length="${thigh_length}"/>
        </geometry>
        <material name="blue"><color rgba="0 0 1 1"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 -${thigh_length/2.0}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${leg_radius}" length="${thigh_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${leg_mass}"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      </inertial>
    </link>

    <joint name="${name}_thigh_joint" type="revolute">
      <parent link="${name}_hip"/>
      <child  link="${name}_thigh"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit lower="-1.57" upper="1.57" effort="10" velocity="1"/>
    </joint>

    <!-- shin -->
    <link name="${name}_shin">
      <visual>
        <origin xyz="0 0 -${shin_length/2.0}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${leg_radius}" length="${shin_length}"/>
        </geometry>
        <material name="red"><color rgba="1 0 0 1"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 -${shin_length/2.0}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${leg_radius}" length="${shin_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${leg_mass}"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      </inertial>
    </link>

    <joint name="${name}_shin_joint" type="revolute">
      <parent link="${name}_thigh"/>
      <child  link="${name}_shin"/>
      <!-- ставим шарнир в конце бедра -->
      <origin xyz="0 0 -${thigh_length}" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit lower="-1.57" upper="1.57" effort="10" velocity="1"/>
    </joint>
  </xacro:macro>

  <!-- ===== четыре лапы ===== -->
  <xacro:leg name="front_left"  x="${body_length/2.0}"  y="${body_width/2.0}"/>
  <xacro:leg name="front_right" x="${body_length/2.0}"  y="-${body_width/2.0}"/>
  <xacro:leg name="rear_left"   x="-${body_length/2.0}" y="${body_width/2.0}"/>
  <xacro:leg name="rear_right"  x="-${body_length/2.0}" y="-${body_width/2.0}"/>

  <!-- ===== ros2_control (интерфейсы суставов) ===== -->
  <!-- Примечание: имя плагина может отличаться в зависимости от установленного пакета (gazebo_ros2_control / gz_ros2_control).
       Если при запуске ros2_control_node увидите pluginlib-ошибку, см. рекомендации ниже. -->
  <ros2_control name="DogSystem" type="system">
    <hardware>
      <!-- частый рабочий вариант для Gazebo Classic; альтернатива: gazebo_ros2_control/DefaultRobotHWSim -->
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>

    <!-- перечисляем все суставы и интерфейсы -->
    <joint name="front_left_hip_joint">
      <command_interface name="position"/>
      <state_interface   name="position"/>
      <state_interface   name="velocity"/>
    </joint>
    <joint name="front_left_thigh_joint">
      <command_interface name="position"/>
      <state_interface   name="position"/>
      <state_interface   name="velocity"/>
    </joint>
    <joint name="front_left_shin_joint">
      <command_interface name="position"/>
      <state_interface   name="position"/>
      <state_interface   name="velocity"/>
    </joint>

    <joint name="front_right_hip_joint">
      <command_interface name="position"/>
      <state_interface   name="position"/>
      <state_interface   name="velocity"/>
    </joint>
    <joint name="front_right_thigh_joint">
      <command_interface name="position"/>
      <state_interface   name="position"/>
      <state_interface   name="velocity"/>
    </joint>
    <joint name="front_right_shin_joint">
      <command_interface name="position"/>
      <state_interface   name="position"/>
      <state_interface   name="velocity"/>
    </joint>

    <joint name="rear_left_hip_joint">
      <command_interface name="position"/>
      <state_interface   name="position"/>
      <state_interface   name="velocity"/>
    </joint>
    <joint name="rear_left_thigh_joint">
      <command_interface name="position"/>
      <state_interface   name="position"/>
      <state_interface   name="velocity"/>
    </joint>
    <joint name="rear_left_shin_joint">
      <command_interface name="position"/>
      <state_interface   name="position"/>
      <state_interface   name="velocity"/>
    </joint>

    <joint name="rear_right_hip_joint">
      <command_interface name="position"/>
      <state_interface   name="position"/>
      <state_interface   name="velocity"/>
    </joint>
    <joint name="rear_right_thigh_joint">
      <command_interface name="position"/>
      <state_interface   name="position"/>
      <state_interface   name="velocity"/>
    </joint>
    <joint name="rear_right_shin_joint">
      <command_interface name="position"/>
      <state_interface   name="position"/>
      <state_interface   name="velocity"/>
    </joint>
  </ros2_control>

  <!-- ===== Gazebo плагин (привязан к base_link) ===== -->
  <gazebo reference="base_link">
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <!-- namespace и параметр робота; gazebo плагин использует robotParam/robotNamespace -->
      <robotNamespace>/dog</robotNamespace>
      <robotParam>/robot_description</robotParam>
      <!-- robotSimType: согласовать с тем, что прописано в <ros2_control>/<hardware>/<plugin>.
           Если используете Ignition (gz), см. gz_ros2_control вместо gazebo_ros2_control. -->
      <robotSimType>gazebo_ros2_control/GazeboSystem</robotSimType>
    </plugin>
  </gazebo>
  <gazebo>
    <sensor type="imu" name="imu_sensor">
      <always_on>true</always_on>
      <update_rate>100.0</update_rate>
      <visualize>true</visualize>
      <topic>imu/data</topic>
    </sensor>
  </gazebo>

</robot>
