<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="dog">

    <xacro:property name="trunk_l" value="0.47543"/> <!-- 475.43  -->
    <xacro:property name="trunk_w" value="0.1807"/>  <!-- 180.7 -->
    <xacro:property name="trunk_h" value="0.1"/>     <!-- -->
    <xacro:property name="trunk_m" value="6.0"/>     <!--  -->

    <xacro:property name="hip_l" value="0.06"/>      <!-- -->
    <xacro:property name="thigh_l" value="0.144"/>   <!-- 144 -->
    <xacro:property name="shin_l" value="0.1525"/>   <!-- 152.5  -->
    <xacro:property name="leg_m" value="0.5"/>       <!-- 0.5  -->
    <xacro:property name="leg_r" value="0.02"/>      <!--  -->

    
    <xacro:macro name="box_inertia" params="m x y z">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
        </inertial>
    </xacro:macro>

    <material name="gray"><color rgba="0.5 0.5 0.5 1"/></material>
    <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>

    <!-- BASE & TRUNK -->
    <link name="base_link"><visual><geometry><box size="0.01 0.01 0.01"/></geometry></visual></link>

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="trunk"/>
    </joint>

    <link name="trunk">
        <visual>
            <geometry><box size="${trunk_l} ${trunk_w} ${trunk_h}"/></geometry>
            <material name="gray"/>
        </visual>
        <collision>
            <geometry><box size="${trunk_l} ${trunk_w} ${trunk_h}"/></geometry>
        </collision>
        <xacro:box_inertia m="${trunk_m}" x="${trunk_l}" y="${trunk_w}" z="${trunk_h}"/>
    </link>

    <!-- LEG MACRO -->
    <xacro:macro name="dog_leg" params="prefix side_x side_y">
        
        <!-- HIP -->
        <joint name="${prefix}_hip_joint" type="revolute">
            <parent link="trunk"/>
            <child link="${prefix}_hip"/>
            <origin xyz="${side_x * trunk_l/2} ${side_y * trunk_w/2} 0" rpy="0 0 0"/>
            <axis xyz="1 0 0"/>
            <limit lower="-0.7" upper="0.7" effort="50" velocity="5"/>
            <dynamics damping="1.0" friction="0.5"/>
        </joint>

        <link name="${prefix}_hip">
            <visual>
                <origin xyz="0 ${side_y * 0.05} 0"/>
                <geometry><box size="0.1 0.1 0.1"/></geometry>
                <material name="black"/>
            </visual>
            <!-- <collision> ... </collision> -->
            <xacro:box_inertia m="0.5" x="0.1" y="0.1" z="0.1"/>
        </link>

        <!-- THIGH -->
        <joint name="${prefix}_thigh_joint" type="revolute">
            <parent link="${prefix}_hip"/>
            <child link="${prefix}_thigh"/>
            <origin xyz="0 ${side_y * 0.05} 0" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <limit lower="-1.5" upper="1.5" effort="50" velocity="5"/>
            <dynamics damping="1.0" friction="0.5"/>
        </joint>

        <link name="${prefix}_thigh">
            <visual>
                <origin xyz="0 0 ${-thigh_l/2}" rpy="0 0 0"/>
                <geometry><cylinder radius="${leg_r}" length="${thigh_l}"/></geometry>
                <material name="gray"/>
            </visual>
            <collision>
                <origin xyz="0 0 ${-thigh_l/2}" rpy="0 0 0"/>
                <geometry><cylinder radius="0.015" length="${thigh_l - 0.04}"/></geometry>
            </collision>
            <xacro:cylinder_inertia m="${leg_m}" r="${leg_r}" h="${thigh_l}"/>
        </link>

        <!-- SHIN -->
        <joint name="${prefix}_shin_joint" type="revolute">
            <parent link="${prefix}_thigh"/>
            <child link="${prefix}_shin"/>
            <origin xyz="0 0 ${-thigh_l}" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <limit lower="-2.5" upper="0.0" effort="50" velocity="5"/>
            <dynamics damping="1.0" friction="0.5"/>
        </joint>

        <link name="${prefix}_shin">
            <visual>
                <origin xyz="0 0 ${-shin_l/2}" rpy="0 0 0"/>
                <geometry><cylinder radius="${leg_r*0.8}" length="${shin_l}"/></geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0 0 ${-shin_l}" rpy="0 0 0"/>
                <geometry><sphere radius="0.04"/></geometry>
                <surface>
                    <friction>
                        <ode><mu>200.0</mu><mu2>200.0</mu2></ode>
                    </friction>
                    <contact>
                        <ode><kp>100000.0</kp><kd>1000.0</kd><min_depth>0.001</min_depth></ode>
                    </contact>
                </surface>
            </collision>
            <xacro:cylinder_inertia m="${leg_m}" r="${leg_r*0.8}" h="${shin_l}"/>
        </link>
    </xacro:macro>

    <xacro:dog_leg prefix="front_left"  side_x="1"  side_y="1"/>
    <xacro:dog_leg prefix="front_right" side_x="1"  side_y="-1"/>
    <xacro:dog_leg prefix="rear_left"   side_x="-1" side_y="1"/>
    <xacro:dog_leg prefix="rear_right"  side_x="-1" side_y="-1"/>

    <ros2_control name="GazeboSystem" type="system">
        <hardware><plugin>gazebo_ros2_control/GazeboSystem</plugin></hardware>

        <joint name="front_left_hip_joint"><command_interface name="position"/><state_interface name="velocity"/><state_interface name="position"><param name="initial_value">0.0</param></state_interface></joint>
        <joint name="front_left_thigh_joint"><command_interface name="position"/><state_interface name="velocity"/><state_interface name="position"><param name="initial_value">0.9</param></state_interface></joint>
        <joint name="front_left_shin_joint"><command_interface name="position"/><state_interface name="velocity"/><state_interface name="position"><param name="initial_value">-1.8</param></state_interface></joint>

        <joint name="front_right_hip_joint"><command_interface name="position"/><state_interface name="velocity"/><state_interface name="position"><param name="initial_value">0.0</param></state_interface></joint>
        <joint name="front_right_thigh_joint"><command_interface name="position"/><state_interface name="velocity"/><state_interface name="position"><param name="initial_value">0.9</param></state_interface></joint>
        <joint name="front_right_shin_joint"><command_interface name="position"/><state_interface name="velocity"/><state_interface name="position"><param name="initial_value">-1.8</param></state_interface></joint>

        <joint name="rear_left_hip_joint"><command_interface name="position"/><state_interface name="velocity"/><state_interface name="position"><param name="initial_value">0.0</param></state_interface></joint>
        <joint name="rear_left_thigh_joint"><command_interface name="position"/><state_interface name="velocity"/><state_interface name="position"><param name="initial_value">0.9</param></state_interface></joint>
        <joint name="rear_left_shin_joint"><command_interface name="position"/><state_interface name="velocity"/><state_interface name="position"><param name="initial_value">-1.8</param></state_interface></joint>

        <joint name="rear_right_hip_joint"><command_interface name="position"/><state_interface name="velocity"/><state_interface name="position"><param name="initial_value">0.0</param></state_interface></joint>
        <joint name="rear_right_thigh_joint"><command_interface name="position"/><state_interface name="velocity"/><state_interface name="position"><param name="initial_value">0.9</param></state_interface></joint>
        <joint name="rear_right_shin_joint"><command_interface name="position"/><state_interface name="velocity"/><state_interface name="position"><param name="initial_value">-1.8</param></state_interface></joint>
    </ros2_control>

    <gazebo>
        <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
            <parameters>$(find dog_controllers)/config/controllers.yaml</parameters>
        </plugin>
    </gazebo>
    <xacro:macro name="foot_physics" params="prefix">
        <gazebo reference="${prefix}_shin">
            <mu1>10.0</mu1>
            <mu2>10.0</mu2>
            
            <kp>1000000.0</kp> 
            <kd>1.0</kd> 
            
            <maxVel>0.0</maxVel> 
            <minDepth>0.002</minDepth>
            
            <material>Gazebo/Black</material>
        </gazebo>
    </xacro:macro>

    <xacro:foot_physics prefix="front_left"/>
    <xacro:foot_physics prefix="front_right"/>
    <xacro:foot_physics prefix="rear_left"/>
    <xacro:foot_physics prefix="rear_right"/>


</robot>