import os

import xacro
from ament_index_python.packages import get_package_share_directory

from launch import LaunchDescription
from launch.actions import ExecuteProcess, RegisterEventHandler, TimerAction
from launch.event_handlers import OnProcessExit
from launch_ros.actions import Node

def generate_launch_description():
    bringup_pkg_share = get_package_share_directory('dog_bringup')
    desc_pkg_share = get_package_share_directory('dog_description')
    brain_pkg_share = get_package_share_directory('dog_brain')

    world_file = os.path.join(bringup_pkg_share, 'worlds', 'dog.world')
    urdf_file = os.path.join(desc_pkg_share, 'urdf', 'dog.urdf.xacro')
    gait_params = os.path.join(brain_pkg_share, 'config', 'gait_params.yaml')

    # Use Python xacro API to avoid the autogenerated '|' header that breaks
    # gazebo_ros2_control rcl argument parser (arguments.c:343).
    doc = xacro.process_file(urdf_file)
    robot_description_str = doc.toxml().replace('|', '')

    robot_description = {"robot_description": robot_description_str}

    node_robot_state_publisher = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        output="screen",
        parameters=[robot_description],
    )

    gazebo = ExecuteProcess(
        cmd=[
            "gazebo",
            "--verbose",
            world_file,
            "-s", "libgazebo_ros_init.so",
            "-s", "libgazebo_ros_factory.so",
        ],
        output="screen",
    )

    # Spawn at z=0.35. Physical joints land at thigh=0, shin=-0.3 (clamped by limits).
    # initial_value=0.5/-1.1 (ef73995 working config) -> PID gently pulls to partial stand.
    spawn_entity = Node(
        package="gazebo_ros",
        executable="spawn_entity.py",
        arguments=[
            "-topic", "robot_description",
            "-entity", "dog",
            "-z", "0.35",
        ],
        output="screen",
    )

    joint_state_broadcaster_spawner = Node(
        package="controller_manager",
        executable="spawner",
        arguments=["joint_state_broadcaster", "--controller-manager", "/controller_manager"],
        output="screen",
    )

    robot_controller_spawner = Node(
        package="controller_manager",
        executable="spawner",
        arguments=["joint_group_position_controller", "--controller-manager", "/controller_manager"],
        output="screen",
    )

    trot_node = Node(
        package="dog_brain",
        executable="trot_node",
        name="trot_node",
        output="screen",
        parameters=[gait_params],
    )

    # Chain: spawn -> JSB -> controller
    delay_jsb_after_spawn = RegisterEventHandler(
        event_handler=OnProcessExit(
            target_action=spawn_entity,
            on_exit=[joint_state_broadcaster_spawner],
        )
    )

    delay_robot_controller_after_jsb = RegisterEventHandler(
        event_handler=OnProcessExit(
            target_action=joint_state_broadcaster_spawner,
            on_exit=[robot_controller_spawner],
        )
    )

    # Wait 4s after controller activates before starting trot_node.
    # Robot needs time to fall from z=0.35 and settle on the ground.
    # Without this delay, trot_node sends large joint commands while robot
    # is still in the air -> PID error -> violent torques -> robot flies.
    start_trot_after_delay = RegisterEventHandler(
        event_handler=OnProcessExit(
            target_action=robot_controller_spawner,
            on_exit=[TimerAction(period=4.0, actions=[trot_node])],
        )
    )

    return LaunchDescription(
        [
            node_robot_state_publisher,
            gazebo,
            spawn_entity,
            delay_jsb_after_spawn,
            delay_robot_controller_after_jsb,
            start_trot_after_delay,
        ]
    )
